var pwNew=await import('playwright');
var devBrowser=await pwNew.chromium.launch({headless:true});
var devContext=await devBrowser.newContext({viewport:{width:1440,height:1000}});
var devPage=await devContext.newPage();
var devErrors=[];
devPage.on('pageerror',e=>devErrors.push(e.message));
await devPage.goto('http://127.0.0.1:5000/#/demo');
await devPage.getByTestId('card-prayer-1').waitFor();
await devPage.evaluate(()=>document.fonts.ready);
await devPage.screenshot({path:'/tmp/tend-inbox-desktop.png',fullPage:true});
await devPage.getByTestId('input-inbox-search').fill('uncertainty');
if(await devPage.getByTestId('card-prayer-2').count()!==1||await devPage.getByTestId('card-prayer-1').count())throw Error('Search failed');
await devPage.getByTestId('input-inbox-search').fill('not a matching request');
await devPage.getByTestId('button-clear-filters').click();
await devPage.getByTestId('checkbox-urgent-only').check();
if(await devPage.getByTestId('text-result-count').innerText()!=='1 request shown')throw Error('Urgent filter failed');
await devPage.getByTestId('checkbox-urgent-only').uncheck();
await devPage.getByTestId('select-category').selectOption('praise');
await devPage.getByTestId('card-prayer-3').waitFor();
await devPage.getByTestId('select-category').selectOption('all');
await devPage.getByTestId('select-sort').selectOption('oldest');
if(await devPage.locator('article.inbox-request').first().getAttribute('data-testid')!=='card-prayer-4')throw Error('Sort failed');
await devPage.getByTestId('button-tab-new').click();
await devPage.getByTestId('button-praying-1').click();
await devPage.getByTestId('button-tab-praying').click();
await devPage.getByTestId('link-prayer-1').click();
await devPage.getByTestId('input-demo-note').fill('Follow up Monday. Fictional note only.');
await devPage.getByTestId('button-demo-save').click();
await devPage.getByText('Sample note saved in this tab.').waitFor();
await devPage.getByTestId('select-demo-status').selectOption('archived');
await devPage.getByRole('button',{name:'Close',exact:true}).click();
await devPage.getByTestId('button-tab-archived').click();
await devPage.getByTestId('link-prayer-1').click();
if(await devPage.getByTestId('input-demo-note').inputValue()!=='Follow up Monday. Fictional note only.')throw Error('Demo note failed');
await devPage.getByRole('button',{name:'Close',exact:true}).click();
await devPage.getByTestId('button-export').click();
var qaDownload=devPage.waitForEvent('download');
await devPage.getByTestId('button-confirm-export').click();
var downloaded=await qaDownload;
console.log('Export filename',downloaded.suggestedFilename());
await downloaded.saveAs('/tmp/tend-qa-export.csv');
await devPage.setViewportSize({width:375,height:812});
await devPage.getByTestId('button-tab-all').click();
await devPage.screenshot({path:'/tmp/tend-inbox-mobile.png',fullPage:true});
if(await devPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
await devPage.emulateMedia({colorScheme:'dark'});
await devPage.reload();
await devPage.getByTestId('card-prayer-1').waitFor();
await devPage.screenshot({path:'/tmp/tend-inbox-dark.png',fullPage:true});
await devPage.goto('http://127.0.0.1:5000/#/church/1/dashboard');
await devPage.getByTestId('link-required-login').waitFor();
console.log('PASS demo search, combined filters, sort, status, modal, notes, export, mobile, dark, and private-route gate.');
console.log('Browser errors',devErrors);
